apply from: 'https://raw.githubusercontent.com/EarthQuestMc/BuiltBrokenScripts/refsbuildScripts/scripts/both/clean.gradle'
apply from: 'https://raw.githubusercontent.com/EarthQuestMc/BuiltBrokenScripts/refsbuildScripts/scripts/both/changelog.gradle'
apply from: 'https://raw.githubusercontent.com/EarthQuestMc/BuiltBrokenScripts/refsbuildScripts/scripts/both/version.gradle'
apply from: 'https://raw.githubusercontent.com/EarthQuestMc/BuiltBrokenScripts/refsbuildScripts/scripts/both/jars.gradle'
apply from: 'https://raw.githubusercontent.com/EarthQuestMc/BuiltBrokenScripts/refsbuildScripts/scripts/both/archive.gradle'
apply from: 'https://raw.githubusercontent.com/EarthQuestMc/BuiltBrokenScripts/refsbuildScripts/scripts/both/repos.gradle'
apply from: 'https://raw.githubusercontent.com/EarthQuestMc/BuiltBrokenScripts/refsbuildScripts/scripts/both/maven.gradle'
