apply from: 'https://raw.githubusercontent.com/EarthQuestMc/BuiltBrokenScripts/refsuniversal/scripts/nonmc/maven.gradle'
apply from: 'https://raw.githubusercontent.com/EarthQuestMc/BuiltBrokenScripts/refsuniversal/scripts/nonmc/version.gradle'
apply from: 'https://raw.githubusercontent.com/EarthQuestMc/BuiltBrokenScripts/refsuniversal/scripts/nonmc/repos.gradle'
apply from: 'https://raw.githubusercontent.com/EarthQuestMc/BuiltBrokenScripts/refsuniversal/scripts/both/clean.gradle'
apply from: 'https://raw.githubusercontent.com/EarthQuestMc/BuiltBrokenScripts/refsuniversal/scripts/both/jars.gradle'
apply from: 'https://raw.githubusercontent.com/EarthQuestMc/BuiltBrokenScripts/refsuniversal/scripts/both/archive.gradle'
apply from: 'https://raw.githubusercontent.com/EarthQuestMc/BuiltBrokenScripts/refsuniversal/scripts/both/repos.gradle'
