apply from: 'https://raw.githubusercontent.com/EarthQuestMc/BuiltBrokenScripts/refsuniversal/scripts/both/clean.gradle'
apply from: 'https://raw.githubusercontent.com/EarthQuestMc/BuiltBrokenScripts/refsuniversal/scripts/both/changelog.gradle'
apply from: 'https://raw.githubusercontent.com/EarthQuestMc/BuiltBrokenScripts/refsuniversal/scripts/both/version.gradle'
//apply from: 'https://raw.githubusercontent.com/EarthQuestMc/BuiltBrokenScripts/refsuniversal/scripts/both/git.gradle'
apply from: 'https://raw.githubusercontent.com/EarthQuestMc/BuiltBrokenScripts/refsuniversal/scripts/both/jars.gradle'
apply from: 'https://raw.githubusercontent.com/EarthQuestMc/BuiltBrokenScripts/refsuniversal/scripts/both/archive.gradle'
apply from: 'https://raw.githubusercontent.com/EarthQuestMc/BuiltBrokenScripts/refsuniversal/scripts/both/idea.gradle'
apply from: 'https://raw.githubusercontent.com/EarthQuestMc/BuiltBrokenScripts/refsuniversal/scripts/both/repos.gradle'
apply from: 'https://raw.githubusercontent.com/EarthQuestMc/BuiltBrokenScripts/refsuniversal/scripts/both/maven.gradle'
apply from: 'https://raw.githubusercontent.com/EarthQuestMc/BuiltBrokenScripts/refsuniversal/scripts/both/dpesBoth.gradle'
